NRI課題のHTMLデータを作成しました。
mb-c16h18n3scl31985/yumi-takahashi pull request #1
Opened 2020-07-29 05:25 UTC by mb-c16h18n3scl31985

2020-07-29 10:58 UTC, n06Ar requested changes
HTMLのレビューをしました
こちらの指摘は必須で修正をお願いいたします

2020-07-29 10:58 UTC, n06Ar commented on index.html
> +    <link rel="icon" href="images/symbol/favicon.ico">
`meta`タグのdescription、keywords、OGP系を追記してください

2020-07-29 10:58 UTC, n06Ar commented on index.html
> +                <li><a href="#"><img src="images/symbol/earth.svg" alt="世界展開"></a></li>
細かいことですが、alt属性は機能的に言語選択などの言語を変更できることを伝えた方が良いですね

2020-07-29 10:58 UTC, n06Ar commented on index.html
> +            <a href="#"><img src="images/symbol/logo.png" alt="ロゴ" class="logo"></a>
alt属性に情報を付け足してください
何のロゴか伝わらない可能性があるためです

2020-07-29 10:58 UTC, n06Ar commented on index.html
> +            <h4>NRIの強み</h4>
`h4`ではなく`h3`にしてください
35行目の`h2`から飛んで`h4`になっています

2020-07-29 10:58 UTC, n06Ar commented on index.html
> +        <h6>Follow Us</h6>
shareだと`p`タグが使われているので統一してください
もし`h6`にする場合は`h`タグの番号に気をつけてください
現状ですと`h5`がないのに`h6`が使用されています

2020-07-29 10:58 UTC, n06Ar commented on index.html
> +    <p>Copyright(c) Nomura Research Institute, Ltd. All rights reserved.</p>
著作権表記は`small`タグで囲うようにしてください
HTML5では、著作権などの表記は`small`タグで囲います
[smallタグ - MDN](https://developer.mozilla.org/ja/docs/Web/HTML/Element/small)

2020-07-29 10:58 UTC, n06Ar commented on index.html
> +            <ul>
明確に分割している理由がなければ、ここは一つの`ul`タグで記述して良いです
見た目のデザインはCSSに役割を分割するためです

2020-07-29 10:58 UTC, n06Ar commented on index.html
> +        <img src="images/h1_whats_2.jpg" alt="背景">
背景画像に意味はないのでalt属性を記載せず`aria-hidden="true"`をつけてください
それか背景画像は、CSSで表示するようにしても良いです

2020-07-29 10:58 UTC, n06Ar commented on index.html
> +        <a href="#" class="article--pdf"><span>&gt;</span>デジタルが開く近未来（NRIのDX）<br>(4.06MB)<img src="images/symbol/icon-pdf.svg" alt="pdfデータ"></a>
背景画像と同様にPDFのアイコンには意味はないのでalt属性を記載せずaria-hidden="true"をつけてください
それか、CSSで表示するようにしても良いです

2020-07-29 10:58 UTC, n06Ar commented on index.html
> +<p class="breadcrumb"><a href="#">NRIトップ </a> &gt; <a href="#">企業情報</a> &gt; <a href="#">NRIの強み : NRIのデジタルビジネス戦略</a></p>
ここの`p`タグは、`header`タグの中に入れて良いです
`header`タグは、ナビゲーションも扱うのとパンくずリストはナビゲーション要素なためです

2020-07-29 11:06 UTC, n06Ar reviewed
CSSに進んだ際に意識して欲しい点をコメントしています
今回のHTMLだと修正は不要ですが、CSSのコーディングでは意識してください

2020-07-29 11:06 UTC, n06Ar commented on index.html
> +    <link rel="stylesheet" href="stylesheet.css">
CSSの提出時にリセットCSSを忘れないでください

2020-07-29 11:06 UTC, n06Ar commented on index.html
> +        <a href="#" class="article--pdf"><span>&gt;</span>デジタルが開く近未来（NRIのDX）<br>(4.06MB)<img src="images/symbol/icon-pdf.svg" alt="pdfデータ"></a>
`&gt;`などの記号は、CSSで扱うようにすると良いです

2020-07-29 12:15 UTC, mb-c16h18n3scl31985 commented
test

2020-07-29 13:20 UTC, n06Ar requested changes
追加で1点指摘を行いました
ご確認をお願いいたします

2020-07-29 13:20 UTC, n06Ar commented on index.html
> +    <meta property="og:image" content="http://www.nri.com/-/media/Corporate/jp/Images/company/whats/story06/story06_s.jpg">
画像は、基本的に直接リンクを避けるようにしてください
`og:image`には、相対パスが設定できないため暫定的に下記のURLを設定してください
`https://github.com/mb-c16h18n3scl31985/yumi-takahashi/blob/9dc8e3983c33f6085b9edd03d279ae64da086d93/images/story06_img_01.jpg?raw=true`

2020-07-30 10:11 UTC, mb-c16h18n3scl31985 commented on index.html
> +        <h6>Follow Us</h6>
`h5`タグに変更いたしました。

2020-07-30 10:11 UTC, mb-c16h18n3scl31985 commented on index.html
> +        <img src="images/h1_whats_2.jpg" alt="背景">
`img`タグ自体を削除し、cssで背景画像を記述することにしました。

2020-07-30 10:12 UTC, mb-c16h18n3scl31985 commented on index.html
> +        <a href="#" class="article--pdf"><span>&gt;</span>デジタルが開く近未来（NRIのDX）<br>(4.06MB)<img src="images/symbol/icon-pdf.svg" alt="pdfデータ"></a>
`img`タグを消去し、cssで表示することにしました。

2020-07-30 10:23 UTC, n06Ar approved these changes
LGTMです！

追加でin my opinion（こうするやり方もある）的なコメントをつけました
修正は一切不要なので、こんなのもあるのか程度に参考にしてください

2020-07-30 10:23 UTC, n06Ar commented on index.html
> +    <table>
CSSで、`ul`と`li`タグを横並びにして表示する方法もあります

2020-07-30 10:23 UTC, n06Ar commented on index.html
> +            <a href="#"><img src="images/symbol/logo.png" alt="NRI ロゴ" class="logo"></a>
主にTOPページでですが、ロゴマークに`h1`タグをつけることもあります
サービスや会社名を大見出しにするとSEO的に良いためです

2020-08-03 05:00 UTC, closed without merging