NRI課題のCSSデータを作成しました。
mb-c16h18n3scl31985/yumi-takahashi pull request #2
Opened 2020-08-03 05:01 UTC by mb-c16h18n3scl31985

ご確認よろしくお願いいたします。

2020-08-03 13:34 UTC, n06Ar requested changes
レビューしました
ご確認をお願いいたします

追記：
カラーコードが`#999`の3文字や`#1a1a1a`のような7文字が混ざっていたので統一をお願いいたします

2020-08-03 13:34 UTC, n06Ar commented on stylesheet.css
> +    background-color: coral;
基本的にカラーコードを使用するようにしてください
またこの背景色は見えないので設定不要です

2020-08-03 13:34 UTC, n06Ar commented on index.html
> +                <ul>
ここは一つの`ul`タグにまとめてください
文書的には一つのリストであるためです
一つにすると一行にまとまりますが`flex-wrap:`を使うと良いです

2020-08-03 13:34 UTC, n06Ar commented on stylesheet.css
> +    margin: 0;
marginが二つあるので不要な方を削除してください

2020-08-03 13:34 UTC, n06Ar commented on index.html
> +        <ul class="global-navi--text">
ここがセンタリングになっているので、右よせ気味にしてください
[このページ](https://coliss.com/articles/build-websites/operation/css/css-flexbox-and-auto-margins.html)がヒントです

2020-08-03 13:34 UTC, n06Ar commented on stylesheet.css
> +body {
safariでみると明朝体になっていました
一応フォント設定を確認してください

2020-08-04 09:45 UTC, mb-c16h18n3scl31985 commented on index.html
> +                <ul>
1つのulにまとめると、2行目の高さが1行目同様に高くなってしまうので、
2行目の要素を`div`タグで囲うなどして高さ調節をすることになり、
ちょっと記述が増えてしまうかなと思ったのですが、如何でしょうか?

2020-08-05 10:58 UTC, n06Ar commented on index.html
> +                <ul>
> 1つのulにまとめると、2行目の高さが1行目同様に高くなってしまうので、
2行目の要素をdivタグで囲うなどして高さ調節をすることになり、

文書的に、`ul`タグを二つにした理由がデザインが理由なのでそれは避けてください
`li`タグの中で`div`タグを使うことは問題ないので良いです

余談ですが、上記の懸念はCSSの一部スタイルを削除しても対応できます

2020-08-05 11:05 UTC, n06Ar requested changes
追加の指摘をしました
ご確認をお願いいたします

別件ですが、html-nri/README.mdは、必要でなければ削除してください

2020-08-05 11:05 UTC, n06Ar commented on html-nri/index.html
> +            <img src="images/story06_img_01.jpg" alt="NRIのビジネス戦略の図">
画像が右寄りなため中央になるようにしてください

2020-08-05 11:05 UTC, n06Ar commented on html-nri/stylesheet.css
> +    border: #333333 1px solid;
`#333333`は元のページと比較して、色が濃いので修正をお願いします

2020-08-06 10:26 UTC, n06Ar requested changes
追加の指摘をしました
ご確認の程をお願いいたします

2020-08-06 10:26 UTC, n06Ar commented on html-nri/index.html
> +        <a href="#"><h1><img src="images/symbol/logo.png" alt="NRI ロゴ" class="logo"></h1></a>
見落としで申し訳ないのですが、このロゴマークの画像は右側に余白をおいてください
元のページでは、このロゴマークの画像は右側に余白があります

2020-08-06 10:26 UTC, n06Ar commented on html-nri/index.html
> +    <div class="footer--bottom">
この`div`タグが左よりのため中央に寄せてください
（`ul`タグと`p`タグの自体は左よりなので問題ないです）

2020-08-06 10:26 UTC, n06Ar commented on html-nri/stylesheet.css
> +    width: 58%;
横幅が少し広めなので、元のページと比較しながら調節してください

2020-08-06 10:26 UTC, n06Ar commented on html-nri/stylesheet.css
> +    margin: 10px;
左右の指定はautoにしてください
10pxで固定なため、横幅が変わると2列になります

2020-08-06 10:36 UTC, mb-c16h18n3scl31985 commented on html-nri/index.html
> +        <a href="#"><h1><img src="images/symbol/logo.png" alt="NRI ロゴ" class="logo"></h1></a>
大変申し訳ありません、仰る意味を掴み損ねています。
元のページですと、ログマークにはmarginなどの距離設定や、ロゴ画像外側にリンク領域はないように思えるのですが、
余白とは何を指していらっしゃるのでしょうか?

2020-08-06 10:40 UTC, n06Ar commented on html-nri/index.html
> +        <a href="#"><h1><img src="images/symbol/logo.png" alt="NRI ロゴ" class="logo"></h1></a>
赤い四角のことです
![余白のスクリーンショット](https://user-images.githubusercontent.com/56122838/89522630-81684680-d81c-11ea-9533-132a199af470.png)

2020-08-06 10:41 UTC, n06Ar commented on html-nri/index.html
> +        <a href="#"><h1><img src="images/symbol/logo.png" alt="NRI ロゴ" class="logo"></h1></a>
赤い四角のことです
![画面のスクリーンショット](https://user-images.githubusercontent.com/56122838/89522770-b70d2f80-d81c-11ea-901c-6878449f9d30.png)

2020-08-06 10:47 UTC, mb-c16h18n3scl31985 commented on html-nri/index.html
> +        <a href="#"><h1><img src="images/symbol/logo.png" alt="NRI ロゴ" class="logo"></h1></a>
恐れ入ります、画像の再現方法がわからないのですが、
画面の大きいメディアですと出てくるのでしょうか?検証ツールでしょうか??

2020-08-06 10:55 UTC, mb-c16h18n3scl31985 commented on html-nri/index.html
> +    <div class="footer--bottom">
stylesheet.css
410-413行目
`.footer--bottom {
    margin: 70px auto 120px auto;
    width: 74%;
}
`

で中央寄せできているかと思っていたのですが、
これではない、ということでしょうか?

※申し訳ありません、githubにおいてPRに対するご指摘のようにコードを引用できればよかったのですが、
調べても方法がわかりませんでした!

2020-08-06 11:01 UTC, n06Ar commented on html-nri/index.html
> +        <a href="#"><h1><img src="images/symbol/logo.png" alt="NRI ロゴ" class="logo"></h1></a>
画面の解像度が1920pxであれば発生します
一旦この指摘は取り下げます
なので対応不要です

2020-08-06 11:12 UTC, mb-c16h18n3scl31985 commented on html-nri/stylesheet.css
> +    margin: 10px;
左右の余白の指定はフレックスボックスのjustify-contentで行うことにして、
margin-bottomに変更しました。

2020-08-06 11:14 UTC, mb-c16h18n3scl31985 commented on html-nri/index.html
> +        <a href="#"><h1><img src="images/symbol/logo.png" alt="NRI ロゴ" class="logo"></h1></a>
そうなのですね。かしこまりました。
何度もお手数おかけして恐れ入ります。

2020-08-06 11:15 UTC, n06Ar commented on html-nri/index.html
> +    <div class="footer--bottom">
答えに近いのであまり言えないのですが、
下記画像のように作っていただいたフッターのリンクリストの横に幅ができています
そのため、元のページと比較してコンテンツが左に寄っているように見えます

- 作っていただいたページのフッター
![作っていただいたページのフッター](https://user-images.githubusercontent.com/56122838/89525359-05bcc880-d821-11ea-9c34-88df2324542b.png)

- 元のページのフッター
![元のページのフッター](https://user-images.githubusercontent.com/56122838/89525467-343aa380-d821-11ea-9eb5-c8b44300c3d7.png)

2020-08-06 11:36 UTC, mb-c16h18n3scl31985 commented on html-nri/index.html
> +    <div class="footer--bottom">
私の画面上では、見た目上同じなのですが、
どのようにすれば上の状況が再現できるでしょうか?

2020-08-06 15:28 UTC, n06Ar commented on html-nri/index.html
> +    <div class="footer--bottom">
画面の横幅が1600px 以上で発生します

2020-08-07 06:05 UTC, mb-c16h18n3scl31985 commented on html-nri/index.html
> +    <div class="footer--bottom">
幅を%指定しているが故に、
画面サイズを広げると要素の幅が広がってしまい、結果的に内包する要素も左寄りになってしまう、と解釈して、
px指定に変えてみたのですが、こちらの変更で合っているでしょうか?
中央寄せと言えるかどうか微妙なのですが・・・!

2020-08-07 10:57 UTC, n06Ar commented on html-nri/index.html
> +    <div class="footer--bottom">
OKです！

2020-08-07 11:01 UTC, n06Ar approved these changes
LGTMです！

2020-08-07 11:20 UTC, n06Ar reviewed
imo（in my opinion）的なコメントを追記しました
参考程度に読んでみてください

2020-08-07 11:20 UTC, n06Ar commented on html-nri/stylesheet.css
> +    display: flex;
`display:table`をする使用して対応しても良いです

2020-08-07 11:20 UTC, n06Ar commented on html-nri/stylesheet.css
> +    width: 1000px;
若干レスポンシブに関わるので知識程度にしておいていただければと思います
PCの横幅を指定する時は、見るひとに寄って画面サイズが異なるため、下記のように最大の横幅と横幅を指定します
```css
width: 100%;
max-width:1000px;
```

2020-08-07 11:20 UTC, n06Ar commented on html-nri/index.html
> +                <p class="prev-article">&lt;<a href="#">ビジネルモデルの特徴</a></p>
見逃していて申し訳ないのですが、`&lt;`は装飾なのでCSSで表示します

2020-08-07 11:20 UTC, n06Ar commented on html-nri/index.html
> +        <p class="breadcrumb"><a href="#">NRIトップ </a><a href="#">企業情報</a><a href="#">NRIの強み : NRIのデジタルビジネス戦略</a></p>
パンくずリストは、リストなので`ul`、`li`タグで書くときがあります

2020-08-07 11:20 UTC, n06Ar commented on html-nri/stylesheet.css
> +    vertical-align: middle;
`display:flex`を使っているので、`vertical-align: middle;`はなくても問題ないです

2020-08-07 11:34 UTC, mb-c16h18n3scl31985 commented on html-nri/stylesheet.css
> +    display: flex;
これ、意味的にどうなのかなと思っていたんですが、
表としての解釈もできるんですね・・・!!!

2020-08-07 11:38 UTC, mb-c16h18n3scl31985 commented on html-nri/stylesheet.css
> +    width: 1000px;
@media(max-width:1000px){・・・}
のように指定するんです・・・よね?
※progateでちょっとだけ齧りました

全体として@media~の大枠で囲って、その内部に色々記述するものと思っていたのですが、
例えば.footer-bottom{・・・}←ここの内部に記述することもあるということでしょうか??

2020-08-07 11:38 UTC, mb-c16h18n3scl31985 commented on html-nri/index.html
> +                <p class="prev-article">&lt;<a href="#">ビジネルモデルの特徴</a></p>
cssにによるものに変更いたしました!

2020-08-07 11:38 UTC, mb-c16h18n3scl31985 commented on html-nri/stylesheet.css
> +    vertical-align: middle;
削除いたしました。

2020-08-07 12:16 UTC, n06Ar commented on html-nri/stylesheet.css
> +    width: 1000px;
>@media(max-width:1000px){・・・}
のように指定するんです・・・よね?
※progateでちょっとだけ齧りました

`@media` （メディアクエリ）の書き方は正解ですが、今回の方法ではメディアクエリでの対応は難しいです。
そのため、[max-width](https://developer.mozilla.org/ja/docs/Web/CSS/max-width)を使用します。
結論から言うと、今回はフッターの一部要素を想定以上に横幅を広げたくない(1000px以内にしたい)ため、`max-width`を使用します。

[max-width](https://developer.mozilla.org/ja/docs/Web/CSS/max-width)とは、要素が画面サイズが指定された値以上（今回だと1000px）にならないように使用するものです。
つまり、**個々の要素の横幅**を条件にして横幅を決定するものです。

`@media` （メディアクエリ）は、メディア（画面やプリント、音声など）毎にスタイルを変更したい場合や画面サイズでスタイルを変更するレスポンシブデザインのために使います。
つまり書いていただいた`@media(max-width:xxxx)`は、**メディア（今回だとブラウザの画面が、）の横幅**を元にスタイルを変更するものです。

整理すると、下記になります。
- [max-width](https://developer.mozilla.org/ja/docs/Web/CSS/max-width)は、特定の要素の横幅が値以上に指定されないようにするもの
- `@media(max-width:xxx)`は、メディア（今回だと画面）の横幅が指定した値以内限定でスタイルを適用するもの

この二つは、役割と対象の範囲が異なります。
そのため今回だと、フッターの一部要素を想定以上に横幅を広げたくない(1000px以内にしたい)ため、`max-width`を使用します。

2020-08-10 12:17 UTC, merged