PHPのひとこと掲示板課題
mb-c16h18n3scl31985/yumi-takahashi pull request #7
Opened 2020-10-03 05:54 UTC by mb-c16h18n3scl31985

2020-10-04 09:44 UTC, n06Ar requested changes
今回の課題に関連するコードに限って、コードレビューをしました。
コードレビューがクリアになったのち、動作確認によるレビューはコードレビュー後に実施します。

2020-10-04 09:44 UTC, n06Ar commented on php-rt-iine/delete.php
> +?>
phpのロジックしかないphpファイルで、php終了タグは書かないようにしてください。
この終了タグの後に改行が含まれている場合予期せぬ動作をする可能性があります。

2020-10-04 09:44 UTC, n06Ar commented on php-rt-iine/index.php
> +function hsc($value)
このような他の画面でも使うような共通なfunctionは、dbconnect.phpのように他のPHPファイルからも使えるようにすると良いです。

2020-10-04 09:44 UTC, n06Ar commented on php-rt-iine/index.php
> +                        <?php echo makeLink(hsc($post['message'])); ?>
`htmlspecialchars`を使用するときは、表示する直前のものに対して使用するようにしてください。
`hsc(makeLink($post['message']));`のようjに使用してください。

2020-10-04 09:44 UTC, n06Ar commented on php-rt-iine/index.php
> +                                    <?php echo retweet_count($db, $post['id']); ?>
retweet_countの戻り値に対してhcsがありません。

2020-10-04 09:44 UTC, n06Ar commented on php-rt-iine/index.php
> +if ($page == '') {
確認ですが、`$_REQUEST['page']`が、確実にstringが入っている理解で良いでしょうか？

2020-10-04 09:44 UTC, n06Ar commented on php-rt-iine/index.php
> +        header('Location: index.php');
ここでリダイレクトをしている意図は何でしょうか？
後続の処理で保存されたデータは読み込まれて画面に表示されるように見えます。

2020-10-04 11:48 UTC, mb-c16h18n3scl31985 commented on php-rt-iine/index.php
> +function hsc($value)
外部に書き出しまして、ついでに見辛さの緩和になればと自作関数も外部データ化しました。
こういった操作が相応しくない場合は、お手数ですがご指摘お願いいたします。

2020-10-04 12:00 UTC, mb-c16h18n3scl31985 commented on php-rt-iine/index.php
> +if ($page == '') {
ご指摘頂いて知識が曖昧であることを自覚しました。

送信部分は下記2つのいずれかです。
- 184行目
`<a href="index.php?page=<?php print($page - 1); ?>">`

- 190行目
`<a href="index.php?page=<?php print($page + 1); ?>">`


URLパラメータで送信された値が空の場合は、36行目により1が代入されます。
```
if ($page == '') {
    $page = 1;
}
```

URLパラメータについて理解が不十分でして、string以外のものが入る可能性について予測が及びません。
恐れ入りますが何かヒントだけでもご教授願えればと思います。

2020-10-04 12:02 UTC, mb-c16h18n3scl31985 commented on php-rt-iine/index.php
> +        header('Location: index.php');
何らかの処理の後`header()`を使う機会が続いていたのか、恐らく反射で入れてしまったものと思います。
消去致しました。
ご指摘ありがとうございます。

2020-10-04 14:55 UTC, n06Ar commented on php-rt-iine/index.php
> +if ($page == '') {
> URLパラメータについて理解が不十分でして、string以外のものが入る可能性について予測が及びません。

何が入るのかわからないのであればemptyなどの関数を利用すれば良いと思います。

2020-10-05 02:18 UTC, mb-c16h18n3scl31985 commented on php-rt-iine/index.php
> +if ($page == '') {
ご返答ありがとうございます。

パラメータで送信される値が想定されない場合、
想定外に備え対処をしておくべきということでしょうか。
上記箇所について`empty`を使って変更しましたので、もしおかしければご指摘願います。

2020-10-05 02:25 UTC, mb-c16h18n3scl31985 commented on php-rt-iine/join/index.php
> +//アップロードファイルのmime_typeを検査
こちらについて、アップロードされた画像の種類を調べるものを自分で試してみたい気持ちがあり、
テキストと異なっています。
念の為ご報告申し上げます。

2020-10-05 05:55 UTC, ykyk1218 commented on php-rt-iine/function/delete.php
> +    $id = $_REQUEST['id'];
idだけだと混乱するので、なんのidなのかが分かる名前がつかられると良いですね😌

2020-10-05 05:55 UTC, ykyk1218 commented on php-rt-iine/function/hsc.php
> +function hsc($value)
[imo]
名前が長いかためこの関数を用意したのだと思います。
悪くはない…とは思うけど、何も知らない人がhscというメソッドを見たときなにこれ？ってなりそうです。🤔

2020-10-05 05:55 UTC, ykyk1218 commented on php-rt-iine/function/retweet.php
> +    $retweet->execute([$_POST['rt_post_id']]);
ここretweet_did関数が使えそうですけど使っていない理由あります？

2020-10-05 07:12 UTC, mb-c16h18n3scl31985 commented on php-rt-iine/function/hsc.php
> +function hsc($value)
私もちょっとどうなのかなと思うのですが、
テキストだと`h()`になっておりまして、せめて少しでもわかりやすくなればとこの名前にしました。

恐らく書籍では、自作関数の紹介を入れるためにこの関数を作ったのだと思うのですが、
他に相応しい名前の案/そもそもこういったショートカットはあまり作らないなど、
何かアドバイス頂けますと幸いです。

2020-10-05 07:32 UTC, mb-c16h18n3scl31985 commented on php-rt-iine/function/retweet.php
> +    $retweet->execute([$_POST['rt_post_id']]);
自作した関数を、自分が新しく作ったphpデータで使うということが単に頭にありませんでした。
ご指摘頂いて視界が開ける思いです。
ありがとうございます。

2020-10-05 12:24 UTC, n06Ar commented on php-rt-iine/function/hsc.php
> +function hsc($value)
CakePHPですと`h()`なので、それに従うのもありかもしれないですね。
それと、PHPDocを書いたりすると、エディタがコメントを表示してくれるので極力書くと良いです。

2020-10-05 12:35 UTC, n06Ar commented on php-rt-iine/index.php
> +function hsc($value)
共通処理でないものは、無理に外部化しなくて良いです。
外部化するにしても、ファイル名にこのファイルで使われていることがわかりそうな命名をしてあげると良いです。

2020-10-05 12:43 UTC, n06Ar requested changes
追加でコメントを行いました。
ご確認をお願いいたします。

2020-10-05 12:43 UTC, n06Ar commented on php-rt-iine/function/view.php
> +                    <img src="../join/member_picture/<?php echo hsc($post['picture']); ?>" width="48" height="48" alt="<?php echo htmlspecialchars($post['name'], ENT_QUOTES); ?>">
前者だとhscを使われていますが、後者だとhtmlspecialchersを使われていますが、後者でhscを使っていないのは、第２引数を使うがために使用している意図で良いでしょうか？
その理解であっているのであれば、hscを修正して、第２引数を受け取れるようにし引数がセットされていない場合は、引数なしのhtmlspecialcharsを使うように修正してください。

2020-10-06 01:43 UTC, mb-c16h18n3scl31985 commented on php-rt-iine/index.php
> +function hsc($value)
短い記述のためあまりする必要はないかもしれないのですが、
複数のデータで使う処理のみを、外部データ化して残すことにしました。
度々お手数おかけして恐れ入りますが、こちらについておかしい場合はご指摘願います。

2020-10-06 01:45 UTC, mb-c16h18n3scl31985 commented on php-rt-iine/function/hsc.php
> +function hsc($value)
> CakePHPですとh()なので

そうなのですね!!!
それでは`h()`に直そうと思います。

また自作の関数に関し、PHPDocを少し追加しました。
こちらについても間違っていないか、ご確認いただければ幸いです。

2020-10-06 01:47 UTC, mb-c16h18n3scl31985 commented on php-rt-iine/function/view.php
> +                    <img src="../join/member_picture/<?php echo hsc($post['picture']); ?>" width="48" height="48" alt="<?php echo htmlspecialchars($post['name'], ENT_QUOTES); ?>">
第2引数は`h()`についているもので、単なる修正ミスでした。
検索と置換を今回あまり使いこなせておらず手直しでしていたので、
今後は置換による変換を心がけたいと思います。
ご指摘ありがとうございます。

2020-10-06 01:48 UTC, mb-c16h18n3scl31985 commented on php-rt-iine/function/retweet.php
> +    $retweet->execute([$_POST['rt_post_id']]);
よく考えればfavorite.php中にも`favorite_did()`が使えることに気づきまして、そちらも修正致しました。

2020-10-08 12:02 UTC, n06Ar requested changes
追加のコメントをしましたので、ご確認をお願いします。

投稿といいね、Retweetができなかったので、ご自身の環境で動作しているか確認をお願いします。

2020-10-08 12:02 UTC, n06Ar commented on php-rt-iine/index.php
> +                        <input type="hidden" name="reply_post_id" value="<?php echo h($_REQUEST['res']); ?>">
`$_REQUEST`に`res`のキーがないケースが考慮されていません。

2020-10-08 12:02 UTC, n06Ar commented on php-rt-iine/index.php
> +                            <?php echo h($message); ?>
`$message`がNULLのケースが考慮されていません。

2020-10-13 12:48 UTC, n06Ar approved these changes
LGTMです！

一応imo的なコメントを1件しておきました。
また、今後に備えた話をすると、データベースにアクセスする一連の処理はfunctionにまとめ引数に値を渡しただけで結果が帰ってくる処理にすると良いです。
functionに役割、責任を分けることで、使い回しや保守性が高くなります。
（このあたりの話はCakePHPで触れます）

2020-10-13 12:48 UTC, n06Ar commented on php-rt-iine/function/shortcut_htmlspecialchars.php
> +function h($value)
`function h(string $value)`として、そもそもstringしか受け付けないようにする方法もあります。
そうすると、この関数の本来のエイリアス的な役割と使用するデータの型の考慮の役割を分離できます。

2020-10-20 10:38 UTC, merged